<?php
include_once "Circle.php";

class Cylinder extends Circle
{
    public $height;

    public function __construct($radius, $height)
    {
        parent::__construct($radius);
        $this->height = $height;
    }

    public function Area()
    {
        return parent::Area() * $this->height; // TODO: Change the autogenerated stub
    }

    public function Par()
    {
        return parent::Par() * $this->height + parent::Area() * 2; // TODO: Change the autogenerated stub
    }

    public function toString()
    {
        echo "Cylinder Area: " . $this->Area();
        echo "<br>";
        echo "Cylinder Par: " . $this->Par();
    }
}